### Neuron Pytorch

In [ ]:
# Single Neuron Model Using Pytorch
# Prof. Fabrício Galende Marques de Carvalho
#
# To install Pytorch, activate your virtual environment and type
# pip3 install torch, or if you want to install all the libraries,
# including Jupyter Notebook, type
# pip3 install -r requirements.txt

import torch
import torch.nn as nn

class Neuron:
    def __init__(self, weights, bias, act_fcn):
        n_features = len(weights)
        self.neuron = nn.Linear(in_features=n_features, out_features=1, bias=True) #dense neuron
        with torch.no_grad(): #no gradient is computed or registered for future use.
            self.neuron.weight[:] = torch.tensor([weights])
            self.neuron.bias[:] = torch.tensor([bias])
        self.act_fcn = act_fcn
        self.pre_act = 0

    def output(self, x):
        self.pre_act = self.neuron(x)
        return self.act_fcn(self.neuron(x))

### Single Neuron Pytorch

In [ ]:
#
# Simple neuron implementation using PyTorch
# Pytorch uses tensors, which can be regarded
# as generalizations of arrays that support differentiation
# and other numerical and computational operations.
#
# Author: Prof. Fabrício Galende Marques de Carvalho
#
import torch

def activation(x):
    return 1. if x>=0 else 0.0

# Float numbers shall include ., otherwise they will be treaded
# as integers.
neuron = Neuron([0.6, 0.4], [-1.], activation)

# Single line, two collumn vector.
# When using Pytorch, each row vector is considered a sample,
# while each collumn is considered a single feature.
# So, the Pytorch model for activation potential (i.e.,
# pre activation, is given by por W.X^T
x = torch.tensor([[0.0, 1.0]])
print("Input: ", x)
print("Post activation:", neuron.output(x))
print("Pre activation: %2.2f" %(neuron.pre_act))

x = torch.tensor([[1.0, 0.0]])
print("Input: ", x)
print("Post activation:", neuron.output(x))
print("Pre activation: %2.2f" %(neuron.pre_act))

x = torch.tensor([[0.0, 0.0]])
print("Input: ", x)
print("Post activation:", neuron.output(x))
print("Pre activation: %2.2f" %(neuron.pre_act))

x = torch.tensor([[1.0, 1.0]])
print("Input: ", x)
print("Post activation:", neuron.output(x))
print("Pre activation: %2.2f" %(neuron.pre_act))

Input:  tensor([[0., 1.]])
Post activation: 0.0
Pre activation: -0.60
Input:  tensor([[1., 0.]])
Post activation: 0.0
Pre activation: -0.40
Input:  tensor([[0., 0.]])
Post activation: 0.0
Pre activation: -1.00
Input:  tensor([[1., 1.]])
Post activation: 1.0
Pre activation: 0.00


/tmp/ipykernel_379/507109195.py:26: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  print("Pre activation: %2.2f" %(neuron.pre_act))


### Pytorch Implementation 1


In [ ]:
import torch
import torch.nn as nn

class Neuron:
    def __init__(self, weights, bias, act_fcn):
        n_features = len(weights)
        self.neuron = nn.Linear(in_features=n_features, out_features=1, bias=True) # dense neuron
        with torch.no_grad(): # no gradient is computed or registered for future use.
            self.neuron.weight[:] = torch.tensor([weights])
            self.neuron.bias[:] = torch.tensor([bias])
        self.act_fcn = act_fcn
        self.pre_act = 0

    def output(self, x):
        self.pre_act = self.neuron(x)
        return self.act_fcn(self.neuron(x))

def linear_function(x):
    return x
neuron1 = Neuron([1., 2.], [0.], linear_function)

x = torch.tensor([[1.0, 1.0]])
print("Input: ", x)
print("Post activation:", neuron1.output(x))
print("Pre activation: %2.2f" %(neuron1.pre_act))

def act_function(x):
  if x >= 0:
    return 3
  else:
    return 0
neuron2 = Neuron([2., 1.], [-1.], act_function)

x = torch.tensor([[1.0, 1.0]])
print("Input: ", x)
print("Post activation:", neuron2.output(x))
print("Pre activation: %2.2f" %(neuron2.pre_act))


Input:  tensor([[1., 1.]])
Post activation: tensor([[3.]], grad_fn=<AddmmBackward0>)
Pre activation: 3.00
Input:  tensor([[1., 1.]])
Post activation: 3
Pre activation: 2.00


### Pytorch Implementation 2

In [ ]:
import torch
import torch.nn as nn

class Neuron:
    def __init__(self, weights, bias, act_fcn):
        n_features = len(weights)
        self.neuron = nn.Linear(in_features=n_features, out_features=1, bias=True) # dense neuron
        with torch.no_grad(): # no gradient is computed or registered for future use.
            self.neuron.weight[:] = torch.tensor([weights])
            self.neuron.bias[:] = torch.tensor([bias])
        self.act_fcn = act_fcn
        self.pre_act = 0

    def output(self, x):
        self.pre_act = self.neuron(x)
        return self.act_fcn(self.neuron(x))

def linear_function(x):
    return x
neuron1 = Neuron([2.], [4.], linear_function)

x = torch.tensor([[1.]])
x2 = neuron1.output(x)
print("Input: ", x)
print("Post activation:", x2)
print("Pre activation: %2.2f" %(neuron1.pre_act))

def reLu(x):
  if x > 1.5:
    return 1.5
  if x < -1.5:
    return -1.5
  else:
    return x

neuron1_2 = Neuron([1.], [0.], reLu)

print("Input: ", x2)
print("Post activation:", neuron1_2.output(x2))
print("Pre activation: %2.2f" %(neuron1_2.pre_act))

Input:  tensor([[1.]])
Post activation: tensor([[6.]], grad_fn=<AddmmBackward0>)
Pre activation: 6.00
Input:  tensor([[6.]], grad_fn=<AddmmBackward0>)
Post activation: 1.5
Pre activation: 6.00


### Tensorflow Neuron

In [ ]:
# Simple neuron model using TensorFlow
#
# Author: Prof. Fabrício Galende M. de Carvalho

import numpy as np
import tensorflow as tf

import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'     # only erros
#tf.config.set_visible_devices([], 'GPU')     # only CPU is used

class NeuronTF:
    def __init__(self, weights, bias, act_fcn):
        n_features = len(weights)

        # One dense neuron just after the input layer
        self.model = tf.keras.Sequential([
            tf.keras.Input(shape=(n_features,)),
            tf.keras.layers.Dense(1, activation=act_fcn)
        ])

        # synaptic weights (n_features, 1)   bias: (1,). It must be noted that the activation
        # potential (pre activation) is given by v = W^T .X^T + bias
        self.weights = np.array(weights, dtype=np.float32).reshape((n_features, 1))
        self.bias    = np.array([bias], dtype=np.float32)

        # Weights and bias that link input layer to dense layer (layers[0] - input layer is not taken into account)
        self.model.layers[0].set_weights([self.weights, self.bias])
        self.pre_act = np.array([0], dtype=np.float32)

    def output(self, x):
        self.pre_act = tf.matmul(x, self.weights) + self.bias
        return self.model(x)

### Tensorflow Single Neuron

In [ ]:
# Single neuron model implementation using TensorFlow.
# In this example, synaptic weights are passed to
# network.
#
# Author: Prof. Fabrício Galende Marques de Carvalho
##

import numpy as np

def activation(x):
    return 1. if x>=0 else 0.0
neuron = NeuronTF([0.6, 0.4], -1.0, activation)
x = np.array([[0.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron.output(x))
print("Pre activation : ", neuron.pre_act)

Neuron output:  0.0
Pre activation :  tf.Tensor([[-0.6]], shape=(1, 1), dtype=float32)


### Tensorflow Implementation 1

In [ ]:
def linear_function(x):
    return x
neuron1 = NeuronTF([1., 2.], 0., linear_function)
x = np.array([[1.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron1.output(x))
print("Pre activation : ", neuron1.pre_act)

def act_function(x):
  if x >= 0:
    return 3
  else:
    return 0
neuron2 = NeuronTF([2., 1.], -1., act_function)
x = np.array([[1.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron2.output(x))
print("Pre activation : ", neuron2.pre_act)

Neuron output:  tf.Tensor([[3.]], shape=(1, 1), dtype=float32)
Pre activation :  tf.Tensor([[3.]], shape=(1, 1), dtype=float32)
Neuron output:  3
Pre activation :  tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


### Tensorflow Implementation 2

In [ ]:
def linear_function(x):
    return x
neuron1 = neuron1 = NeuronTF([2.], 4., linear_function)
x = np.array([[1.]], dtype= np.float32)
x2 = neuron1.output(x)
print("Neuron output: ", x2)
print("Pre activation : ", neuron1.pre_act)

def reLu(x):
  if x > 1.5:
    return 1.5
  if x < -1.5:
    return -1.5
  else:
    return x
neuron1_2 = NeuronTF([1.], 0., reLu)
print("Neuron output: ", neuron1_2.output(x2))
print("Pre activation : ", neuron1_2.pre_act)

Neuron output:  tf.Tensor([[6.]], shape=(1, 1), dtype=float32)
Pre activation :  tf.Tensor([[6.]], shape=(1, 1), dtype=float32)
Neuron output:  1.5
Pre activation :  tf.Tensor([[6.]], shape=(1, 1), dtype=float32)
